import { createRequestHandler } from "@remix-run/cloudflare";
// @ts-ignore - this is generated by the build
import * as build from "./build/server/index.js";

const handleRequest = createRequestHandler(build, "production");

export default {
    async fetch(request: Request, env: any, ctx: any) {
        try {
            // Try to serve static assets first
            if (env.ASSETS) {
                const url = new URL(request.url);
                if (url.pathname.startsWith("/assets/") || url.pathname.startsWith("/build/") || url.pathname.startsWith("/favicon.ico")) {
                    const response = await env.ASSETS.fetch(request);
                    if (response.status < 400) {
                        return response;
                    }
                }
            }
        } catch (e) {
            // Ignore error and fall back to app
        }

        return handleRequest(request, {
            cloudflare: {
                env,
                ctx,
                cf: request.cf!,
            },
        });
    },
};
